# Generated by Django 2.2.2 on 2019-06-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albergatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('citta', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nLetti', models.IntegerField()),
                ('prezzo', models.FloatField()),
                ('servizi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('checkIn', models.DateField()),
                ('checkOut', models.DateField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgettoISW.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('citta', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=100)),
                ('albergatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgettoISW.Albergatore')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgettoISW.Hotel'),
        ),
    ]
