# Generated by Django 2.2.2 on 2019-06-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgettoISW', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='citta',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
